versions:
  "5":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      PLATFORM_VERSION: "5.0.16"
    test_config:
      cmd:
        - git --version
        - platform --version
        - python --version
        - pip --version
        - pipenv --version
