test_config: &test_config
  cmd:
    - aws --version
    - gitleaks version
    - go version
    - golangci-lint --version
    - migrate -version
    - mockgen -version
    - modd --version
    - rsync --version
    - swagger version

versions:
  "1.21":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
  "1.22":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
  "1.23":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
