sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=ansible       VERSION=2.3.0.0-r1 PYTHON_VERSION=2.7.14-r0
    - env: LANGUAGE=aws           VERSION=1
    - env: LANGUAGE=dind-aws      VERSION=1    DOCKER_COMPOSE_VERSION=1.20.1 GLIBC_VERSION=2.23-r3
    - env: LANGUAGE=golang        VERSION=1.9  GLIDE_VERSION=v0.13.1
    - env: LANGUAGE=java          VERSION=8    JAVA_VERSION=8u171-1~webupd8~0
    - env: LANGUAGE=node          VERSION=6.14 NODE_VERSION=6.14.1 NPM_VERSION=3.10.10
    - env: LANGUAGE=node          VERSION=8.11 NODE_VERSION=8.11.1 NPM_VERSION=5.6.0
    - env: LANGUAGE=node          VERSION=9.10 NODE_VERSION=9.10.1  NPM_VERSION=5.6.0
    - env: LANGUAGE=php           VERSION=5.3  PHP_VERSION=5.3.10 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.6 SECURITY_CHECKER_VERSION=2.0.6
    - env: LANGUAGE=php           VERSION=5.6  PHP_VERSION=5.6.35-cli-alpine APCU_VERSION=4.0.11 COMPOSER_VERSION=1.6.3 REDIS_VERSION=4.0.0 SECURITY_CHECKER_VERSION=4.1.6 XDEBUG_VERSION=XDEBUG_2_5_5
    - env: LANGUAGE=php           VERSION=7.1  PHP_VERSION=7.1.16-cli-alpine APCU_VERSION=5.1.11 COMPOSER_VERSION=1.6.3 REDIS_VERSION=4.0.0 SECURITY_CHECKER_VERSION=4.1.8 XDEBUG_VERSION=2.6.0
    - env: LANGUAGE=python        VERSION=2.7  PYTHON_VERSION=2.7.15
    - env: LANGUAGE=python        VERSION=3.6  PYTHON_VERSION=3.6.5
    - env: LANGUAGE=react-native  VERSION=1    JAVA_VERSION=8u171-1~webupd8~0
    - env: LANGUAGE=ruby          VERSION=2.5
    - env: LANGUAGE=sonar         VERSION=3.0  GLIBC_VERSION=2.23-r3 SONARSCANNER_VERSION=3.0.3.778

script:
    - travis_wait python travis.py
