sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=ansible      VERSION=2.5.5-r0 PYTHON_VERSION=2.7.15-r1
    - env: LANGUAGE=arachni      VERSION=1.5      ARACHNI_VERSION=1.5.1 ARACHNI_WEB_UI_VERSION=0.5.12
    - env: LANGUAGE=chrome       VERSION=1
    - env: LANGUAGE=aws          VERSION=1        PIP_VERSION=18.1 PIPENV_VERSION=2018.10.13
    - env: LANGUAGE=dind-aws     VERSION=1        DOCKER_COMPOSE_VERSION=1.22.0 GLIBC_VERSION=2.27-r0 PIP_VERSION=18.1 PIPENV_VERSION=2018.10.13
    - env: LANGUAGE=golang       VERSION=1.9      GLIDE_VERSION=v0.13.1
    - env: LANGUAGE=java         VERSION=6        MAVEN_VERSION=3.2.5
    - env: LANGUAGE=java         VERSION=8        JAVA_VERSION=8u171-jdk-slim
    - env: LANGUAGE=java         VERSION=10       JAVA_VERSION=10.0.1-jdk-slim
    - env: LANGUAGE=java         VERSION=11       JAVA_VERSION=11-jdk-slim
    - env: LANGUAGE=node         VERSION=6.14     NODE_VERSION=6.14.4  NPM_VERSION=3.10.10  NVM_VERSION=0.33.11
    - env: LANGUAGE=node         VERSION=8.12     NODE_VERSION=8.12.0  NPM_VERSION=6.4.1    NVM_VERSION=0.33.11
    - env: LANGUAGE=node         VERSION=10.10    NODE_VERSION=10.11.0 NPM_VERSION=6.4.1    NVM_VERSION=0.33.11
    - env: LANGUAGE=php          VERSION=5.6      PHP_VERSION=5.6.38-cli-alpine APCU_VERSION=4.0.11 COMPOSER_VERSION=1.6.5 MEMCACHED_VERSION=2.2.0 REDIS_VERSION=4.1.1 SECURITY_CHECKER_VERSION=4.1.6 SSH2_VERSION=0.13 XDEBUG_VERSION=XDEBUG_2_5_5
    - env: LANGUAGE=php          VERSION=7.1      PHP_VERSION=7.1.22-cli-alpine APCU_VERSION=5.1.12 COMPOSER_VERSION=1.7.2 MEMCACHED_VERSION=3.0.4 REDIS_VERSION=4.1.1 SECURITY_CHECKER_VERSION=4.1.8 SSH2_VERSION=1.1.2 XDEBUG_VERSION=2.6.1
    - env: LANGUAGE=php          VERSION=7.2      PHP_VERSION=7.2.10-cli-alpine APCU_VERSION=5.1.12 COMPOSER_VERSION=1.7.2 MEMCACHED_VERSION=3.0.4 REDIS_VERSION=4.1.1 SECURITY_CHECKER_VERSION=4.1.8 SSH2_VERSION=1.1.2 XDEBUG_VERSION=2.6.1
    - env: LANGUAGE=python       VERSION=2.7      PYTHON_VERSION=2.7.15 PIP_VERSION=18.1 PIPENV_VERSION=2018.10.13
    - env: LANGUAGE=python       VERSION=3.7      PYTHON_VERSION=3.7.0 PIP_VERSION=18.1 PIPENV_VERSION=2018.10.13
    - env: LANGUAGE=react-native VERSION=1
    - env: LANGUAGE=ruby         VERSION=2.5
    - env: LANGUAGE=sonar        VERSION=3.2      GLIBC_VERSION=2.27-r0 SONARSCANNER_VERSION=3.2.0.1227

script:
    - travis_wait python travis.py
