sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node     VERSION=6.11 NODE_VERSION=6.11.3
    - env: LANGUAGE=node     VERSION=7.10 NODE_VERSION=7.10.1
    - env: LANGUAGE=node     VERSION=8.6  NODE_VERSION=8.6.0
    - env: LANGUAGE=java     VERSION=8    JAVA_VERSION=8u151-1~webupd8~0
    - env: LANGUAGE=php      VERSION=5.3  PHP_VERSION=5.3.10 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.4 SECURITY_CHECKER_VERSION=2.0.6
    - env: LANGUAGE=php      VERSION=5.6  PHP_VERSION=5.6.31 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.4 SECURITY_CHECKER_VERSION=4.1.6
    - env: LANGUAGE=php      VERSION=7.1  PHP_VERSION=7.1.9  PHP_BUILD_INSTALL_EXTENSION=apcu=5.1.8  REDIS_VERSION=3.1.4 SECURITY_CHECKER_VERSION=4.1.6
    - env: LANGUAGE=aws      VERSION=1
    - env: LANGUAGE=dind-aws VERSION=1    DOCKER_COMPOSE_VERSION=1.16.1
    - env: LANGUAGE=golang   VERSION=1.9  GLIDE_VERSION=v0.13.0
    - env: LANGUAGE=ruby     VERSION=2.4
    - env: LANGUAGE=ansible  VERSION=2.3.0.0-r1 PYTHON_VERSION=2.7.13-r1 GLIBC_VERSION=2.26-r0
    - env: LANGUAGE=sonar    VERSION=3.0  SONARSCANNER_VERSION=3.0.3.778

script:
    - travis_wait python travis.py
