---
docker_hub_namespace: &docker_hub_namespace ekino

# Common build_vars
CI_HELPER_VERSION: &CI_HELPER_VERSION 0.0.6
ci_helper_test: &ci_helper_test ci-helper version -e
MODD_VERSION: &MODD_VERSION 0.5
TASKFILE_VERSION: &TASKFILE_VERSION 2.8.1

ansible_tests: &ansible_tests
  cmd:
    - python --version
    - pip --version
    - ansible --version
    - ansible-playbook --version

terraform_tests: &terraform_tests
  cmd:
    - terraform version
    - terragrunt --version
    - terraform-compliance --version
    - python --version
    - aws --version
    - git --version
    - infracost --version

ansible:
  "2.9":
    template_vars:
      BASE_IMAGE_VERSION: 3.8
    build_args:
      ANSIBLE_VERSION: 2.9.10
    test_config: *ansible_tests

aws:
  "1":
    build_args:
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - aws --version
        - pip --version
        - pipenv --version
        - git --version
        - rsync --version
        - zip --version
        - task --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8

awslnx-systemd:
  "2":
    template_vars:
      BASE_IMAGE_VERSION: 2.0.20190508
    test_config:
      cmd:
        - python --version
        - pip --version

azure:
  "2":
    build_args:
      AZURE_CLI_VERSION: 2.10.1
      TERRAFORM_VERSION: 0.12.29
    test_config:
      cmd:
        - az --version
        - terraform --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8

bitcoind:
  "0.20.0":
    build_args:
      BITCOIN_VERSION: 0.20.0
      BITCOIN_SHA256: 35ec10f87b6bc1e44fd9cd1157e5dfa483eaf14d7d9a9c274774539e7824c427
    test_config:
      cmd:
        - bitcoind --version

chrome:
  "1":
    build_args:
      MODD_VERSION: *MODD_VERSION
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - google-chrome --no-sandbox --version
        - google-chrome-unstable --no-sandbox --version
        - node --version
        - npm --version
        - yarn --version
        - task --version

dind:
  "1":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      DOCKER_COMPOSE_VERSION: 1.25.0
      GLIBC_VERSION: 2.27-r0
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
      AZURE_CLI_VERSION: 2.10.1
      TRIVY_VERSION: "0.15.0"
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - az version
        - docker --version
        - docker-compose --version
        - task --version
        - trivy --version

golang:
  "1.15":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      GITLEAKS_VERSION: 6.1.2
      GOLANGCILINT_VERSION: 1.31.0
      GOMODUPGRADE_VERSION: 0.2.1
      GOSWAGGER_VERSION: 0.25.0
      MIGRATE_VERSION: 4.12.2
      MOCKGEN_VERSION: 1.4.3
      MODD_VERSION: 0.8
      TESTFIXTURES_VERSION: 3.4.0
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - gitleaks --version
        - go version
        - golangci-lint --version
        - migrate -version
        - mockgen -version
        - modd --version
        - rsync --version
        - swagger version
        - testfixtures --version

    template_vars:
      BASE_IMAGE_VERSION: 1.15.2

java_test_config: &java_test_config
  cmd:
    - *ci_helper_test
    - java -version
    - mvn --version
    - aws --version
    - modd --version
    - dot -V
    - jq --version
    - psql --version

java:
  "8":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
    test_config: *java_test_config
    template_vars:
      BASE_IMAGE_VERSION: 8
      JAVA_VERSION: jdk8u282-b08-debian-slim
  "11":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
    test_config: *java_test_config
    template_vars:
      BASE_IMAGE_VERSION: 11
      JAVA_VERSION: jdk-11.0.10_9-debian-slim

kubectl:
  "1.20":
    test_config:
      cmd:
        - eksctl version
        - kube-score version
        - kubectx
        - kubeval --version
        - kustomize version
        - helm version
        - aws --version
    build_args:
      EKSCTL_VERSION: 0.36.0
      KUBECTL_VERSION: 1.20.2
      KUBECTX_VERSION: 0.9.1
      KUBESCORE_VERSION: 1.10.0
      KUBEVAL_VERSION: 0.15.0
      KUSTOMIZATION_VERSION: 3.9.2
      HELM_VERSION: 3.5.0

node_test_config: &node_test_config
  cmd:
    - *ci_helper_test
    - node --version
    - npm --version
    - yarn --version
    - sass --version
    - modd --version
    - task --version

node:
  "10":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 10.21.0
      NPM_VERSION: 6.14.5
      NVM_VERSION: 0.35.3
      MODD_VERSION: *MODD_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config: *node_test_config
  "12":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 12.18.1
      NPM_VERSION: 6.14.5
      NVM_VERSION: 0.35.3
      MODD_VERSION: *MODD_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config: *node_test_config
  "14":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 14.4.0
      NPM_VERSION: 6.14.5
      NVM_VERSION: 0.35.3
      MODD_VERSION: *MODD_VERSION
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config: *node_test_config

php_test_config: &php_test_config
  volume: php:/tmp
  cmd:
    - *ci_helper_test
    - php --version
    - composer --version
    - modd --version
    - php-cs-fixer --version
    - security-checker -help
    - php /tmp/test.php

php_build_args: &php_build_args
  APCU_VERSION: 5.1.19
  CI_HELPER_VERSION: *CI_HELPER_VERSION
  COMPOSER_VERSION: 2.0.8
  ICONV_VERSION: 1.15-r2
  MEMCACHED_VERSION: 3.1.5
  MODD_VERSION: *MODD_VERSION
  MUSL_VERSION: 1.1.24-r10
  PHP_CS_FIXER_VERSION: 2.18.0
  REDIS_VERSION: 5.3.2
  SECURITY_CHECKER_VERSION: 1.0.0
  SSH2_VERSION: 1.2
  XDEBUG_VERSION: 2.9.8

php:
  "7.2":
    build_args: *php_build_args
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.2.34-cli-alpine
  "7.3":
    build_args: *php_build_args
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.3.24-cli-alpine
  "7.4":
    build_args: *php_build_args
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.4.12-cli-alpine
  "8.0":
    build_args:
      APCU_VERSION: 5.1.19
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      COMPOSER_VERSION: 2.0.8
      ICONV_VERSION: 1.15-r2
      MEMCACHED_VERSION: 3.1.5
      MODD_VERSION: *MODD_VERSION
      MUSL_VERSION: 1.1.24-r10
      PHP_CS_FIXER_VERSION: 2.18.0
      REDIS_VERSION: 5.3.2
      SECURITY_CHECKER_VERSION: 1.0.0
      SSH2_VERSION: 1.2
      XDEBUG_VERSION: 3.0.2
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 8.0.0-cli-alpine

platformsh:
  "3.64":
    build_args:
      PLATFORMSH_CLI_VERSION: "3.64.6"
      PLATFORMSH_CLI_SHASUM: "66dfabcaeceda58df9dfdf71c1a6110034e907c834b908298f37c5be2ccdd638"
    test_config:
      cmd:
        - php --version
        - platform --version
        - python --version
        - pip --version

python_tests: &python_tests
  cmd:
    - pip --version
    - python --version
    - aws --version

python:
  "3.6":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.6.12
  "3.7":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.7.9
  "3.8":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8.7
  "3.9":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.9.1

pynode_tests: &pynode_tests
  cmd:
    - pip --version
    - python --version
    - node --version
    - npm --version
    - aws --version

pynode:
  "3.8":
    test_config: *pynode_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8
  "3.7":
    test_config: *pynode_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.7

react-native:
  "2":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
      NODE_VERSION: 12.13.0
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - node --version
        - npm --version
        - modd --version
        - react-native --version
        - rnpm --version
        - yarn --version

ruby:
  "2.6":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - bundle --version
        - *ci_helper_test
        - ruby --version

scoutsuite:
  "5.10":
    build_args:
      SCOUTSUITE_VERSION: 5.10.1
    test_config:
      cmd:
        - pip --version
        - pipenv --version
        - scout --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8

sonar:
  "4.6":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      GLIBC_VERSION: 2.32-r0
      SONARSCANNER_VERSION: 4.6.0.2311
      ZLIB_VERSION: 1.2.11-3
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - sonar-scanner -v

terraform:
  "0.12.30":
    build_args:
      TERRAFORM_VERSION: 0.12.30
      TERRAGRUNT_VERSION: 0.27.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.12
      INFRACOST_VERSION: 0.7.13
    test_config: *terraform_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8
  "0.13.6":
    build_args:
      TERRAFORM_VERSION: 0.13.6
      TERRAGRUNT_VERSION: 0.27.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.12
      INFRACOST_VERSION: 0.7.13
    test_config: *terraform_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8
  "0.14.5":
    build_args:
      TERRAFORM_VERSION: 0.14.5
      TERRAGRUNT_VERSION: 0.27.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.12
      INFRACOST_VERSION: 0.7.13
    test_config: *terraform_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8

tezosqa:
  "0.1":
    template_vars:
      BASE_IMAGE_VERSION: 3.8
    build_args:
      SMARTPY_VERSION: 20201128-b860cdfdedfe18b3c3538d581fb7d175284a8136
    test_config:
      cmd:
        - /opt/SmartPy/SmartPy.sh --version
