---
docker_hub_namespace: &docker_hub_namespace ekino

# Common build_vars
CI_HELPER_VERSION: &CI_HELPER_VERSION 0.0.6
ci_helper_test: &ci_helper_test ci-helper version -e
MODD_VERSION: &MODD_VERSION 0.5

ansible_tests: &ansible_tests
  cmd:
    - python --version
    - pip --version
    - ansible --version
    - ansible-playbook --version

ansible:
  "2.9":
    template_vars:
      BASE_IMAGE_VERSION: 3.8
    build_args:
      ANSIBLE_VERSION: 2.9.5
    test_config: *ansible_tests

arachni:
  "1.5":
    build_args:
      ARACHNI_VERSION: 1.5.1
      ARACHNI_WEB_UI_VERSION: 0.5.12
    test_config:
      cmd:
        - arachni --version

aws:
  "1":
    test_config:
      cmd:
        - aws --version
        - pip --version
        - pipenv --version
        - git --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8

awslnx-systemd:
  "2":
    template_vars:
      BASE_IMAGE_VERSION: 2.0.20190508
    test_config:
      cmd:
        - python --version
        - pip --version

azure:
  "2":
    build_args:
      AZURE_CLI: 2.1.0
      TERRAFORM_VERSION: 0.12.21
    test_config:
      cmd:
        - az --version
        - terraform --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8

chrome:
  "1":
    build_args:
      MODD_VERSION: *MODD_VERSION
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - google-chrome --no-sandbox --version
        - google-chrome-unstable --no-sandbox --version
        - node --version
        - npm --version
        - yarn --version

dind-aws:
  "1":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      DOCKER_COMPOSE_VERSION: 1.25.0
      GLIBC_VERSION: 2.27-r0
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - docker --version
        - docker-compose --version

golang:
  "1.14":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - go version
    template_vars:
      BASE_IMAGE_VERSION: 1.14

ibm:
  "1.2":
    build_args:
      TERRAFORM_VERSION: 0.12.23
      IBM_PROVIDER_VERSION: 1.2.1
      IBM_CLI_VERSION: 0.22.0
      IBM_NULL_PROVIDER_VERSION: 2.1.2
    test_config:
      cmd:
        - terraform version
        - ibmcloud version
        - ibmcloud plugin list
    template_vars:
      BASE_IMAGE_VERSION: 1.14.0

java_test_config: &java_test_config
  cmd:
    - *ci_helper_test
    - java -version
    - mvn --version
    - aws --version
    - modd --version
    - dot -V
    - jq --version
    - psql --version

java:
  "8":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
    test_config: *java_test_config
    template_vars:
      BASE_IMAGE_VERSION: 8
      JAVA_VERSION: jdk8u242-b08-debian-slim
  "11":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
    test_config: *java_test_config
    template_vars:
      BASE_IMAGE_VERSION: 11
      JAVA_VERSION: jdk-11.0.6_10-debian-slim

kubectl:
  "1.16":
    test_config:
      cmd:
        - eksctl version
        - kube-score version
        - kubectx
        - kubeval --version
        - kustomize version
    build_args:
      EKSCTL_VERSION: 0.13.0
      KUBECTL_VERSION: 1.17.3
      KUBECTX_VERSION: 0.8.0
      KUBESCORE_VERSION: 1.5.0
      KUBEVAL_VERSION: 0.14.0
      KUSTOMIZATION_VERSION: 3.5.4

node_test_config: &node_test_config
  cmd:
    - *ci_helper_test
    - node --version
    - npm --version
    - yarn --version
    - sass --version
    - modd --version

node:
  "10":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 10.19.0
      NPM_VERSION: 6.13.7
      NVM_VERSION: 0.34.0
      MODD_VERSION: *MODD_VERSION
    test_config: *node_test_config
  "12":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 12.16.1
      NPM_VERSION: 6.13.7
      NVM_VERSION: 0.34.0
      MODD_VERSION: *MODD_VERSION
    test_config: *node_test_config

php_test_config: &php_test_config
  volume: php:/tmp
  cmd:
    - *ci_helper_test
    - php --version
    - composer --version
    - modd --version
    - php-cs-fixer --version
    - security-checker --version
    - php /tmp/test.php

php_build_args: &php_build_args
  APCU_VERSION: 5.1.18
  CI_HELPER_VERSION: *CI_HELPER_VERSION
  COMPOSER_VERSION: 1.9.1
  MEMCACHED_VERSION: 3.1.4
  MODD_VERSION: *MODD_VERSION
  PHP_CS_FIXER_VERSION: 2.16.1
  REDIS_VERSION: 5.1.1
  SECURITY_CHECKER_VERSION: 6.0.3
  SSH2_VERSION: 1.2
  XDEBUG_VERSION: 2.8.0

php:
  "7.2":
    build_args: *php_build_args
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.2.25-cli-alpine
  "7.3":
    build_args: *php_build_args
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.3.12-cli-alpine
  "7.4":
    build_args: *php_build_args
    test_config: *php_test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.4.0-cli-alpine

platformsh:
  "3.50":
    build_args:
      PLATFORMSH_CLI_VERSION: "3.50.1"
      PLATFORMSH_CLI_SHASUM: "d055e534fc71ce907a4111c55ce69e30ddb2dcc1b02aad7764d395872fc84e2e"
    test_config:
      cmd:
        - php --version
        - platform --version
        - python --version
        - pip --version

python_tests: &python_tests
  cmd:
    - pip --version
    - python --version
    - aws --version

python:
  "2.7":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 2.7.16
  "3.6":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.6.10
  "3.7":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.7.6
  "3.8":
    test_config: *python_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8.1

pynode_tests: &pynode_tests
  cmd:
    - pip --version
    - python --version
    - node --version
    - npm --version
    - aws --version

pynode:
  "3.8":
    test_config: *pynode_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.8
  "3.7":
    test_config: *pynode_tests
    template_vars:
      BASE_IMAGE_VERSION: 3.7

react-native:
  "2":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
      NODE_VERSION: 12.13.0
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - node --version
        - npm --version
        - modd --version
        - react-native --version
        - rnpm --version
        - yarn --version

ruby:
  "2.6":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - bundle --version
        - *ci_helper_test
        - ruby --version

scoutsuite:
  "5.7":
    build_args:
      SCOUTSUITE_VERSION: 5.7.0
    test_config:
      cmd:
        - pip --version
        - pipenv --version
        - scout --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8

sonar:
  "3.3":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      GLIBC_VERSION: 2.27-r0
      SONARSCANNER_VERSION: 3.3.0.1492
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - sonar-scanner -v

terraform:
  "0.12":
    build_args:
      TERRAFORM_VERSION: 0.12.20
    test_config:
      cmd:
        - terraform version
        - python --version
        - aws --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8
