versions:
  "0.12":
    build_args:
      TERRAFORM_VERSION: 0.12.24
    test_config:
      cmd:
        - terraform version
        - python --version
        - aws --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8
