test_config: &test_config
  cmd:
    - terraform version
    - terraform-compliance --version
    - python --version
    - aws --version
    - git --version
    - az --version
    - gcloud --version
    - infracost --version
    - terragrunt --version

versions:
  "1.1.5":
    build_args:
      TERRAFORM_VERSION: 1.2.1
      TERRAGRUNT_VERSION: 0.37.1
      INFRACOST_VERSION: 0.10.0
    test_config: *test_config
    platforms: *base_platforms
