test_config: &test_config
  cmd:
    - terraform version
    - terragrunt --version
    - terraform-compliance --version
    - python --version
    - aws --version
    - git --version
    - infracost --version
    - az --version

versions:
  "1.0.11":
    build_args:
      TERRAFORM_VERSION: 1.0.11
      TERRAGRUNT_VERSION: 0.35.12
      INFRACOST_VERSION: 0.9.13
    test_config: *test_config
