versions:
  "1.24":
    platforms: *base_platforms
    test_config:
      cmd:
        - kube-score version
        - kubeval --version
        - kubent
        - kustomize version
        - helm version
        - aws --version
        - helm diff version
        - trivy --version
    build_args:
      HELM_DIFF_VERSION: 3.5.0
      HELM_VERSION: 3.9.0
      KUBECTL_VERSION: 1.24.0
      KUBENT_VERSION: 0.5.1
      KUBESCORE_VERSION: 1.14.0
      KUBEVAL_VERSION: 0.16.1
      KUSTOMIZATION_VERSION: 4.5.5
      TRIVY_VERSION: "0.28.1"
